---
title: My Jekyll Page
date: 2021-04-19
---

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a brief description for this basic GitHub page using the minima theme. 

# social links
github_username:  witkie123

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
